sudo: true
language: go
env:
- GO111MODULE=off
-
go:
- 1.11.5
-
git:
  depth: 1

notifications:
  email: false

before_install:
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet version
- gcloud --quiet components updatel


install:
- go get -u github.com/golang/dep/...
- dep ensure -v
- gcloud config set project logmate-api

script:
- go test -v -race ./...

deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy/prod/deploy-prod.sh
  on:
    branch: master
